import { BrowserWindow, screen } from "electron";
import log from "electron-log/main";
import LensOverlay from "../../main/managers/LensOverlay";
import Window from "../../main/managers/Window";
import type { KeyboardModel, LensSettings, LensState } from "../shared/types";
import { getLensSettings } from "./lens-settings";

// Magic constants auto-generated by Forge's Webpack plugin for the lens_window
// renderer entry point (dev-server URL in development, file:// path when packaged).
declare const LENS_WINDOW_WEBPACK_ENTRY: string;
declare const LENS_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

let overlayVisible = false;
let overlayStyleApplied = false;
let normalBounds: Electron.Rectangle | null = null;
let overlayBounds: Electron.Rectangle | null = null;
let overlayLockedSize: { width: number; height: number } | null = null;
let fixingOverlayResize = false;

function getWin(): BrowserWindow | null {
  return LensOverlay.getWindow();
}

export function overlayAlive(): boolean {
  const win = getWin();
  return win !== null && !win.isDestroyed();
}

export function isOverlayVisible(): boolean {
  return overlayVisible;
}

function guardOverlayResize(): void {
  const win = getWin();
  if (!win || !overlayLockedSize || fixingOverlayResize) return;
  const { width, height } = win.getBounds();
  if (width !== overlayLockedSize.width || height !== overlayLockedSize.height) {
    fixingOverlayResize = true;
    win.setSize(overlayLockedSize.width, overlayLockedSize.height);
    setImmediate(() => {
      fixingOverlayResize = false;
    });
  }
}

function preventOverlayResize(e: { preventDefault(): void }): void {
  e.preventDefault();
}

export function applyOverlayMode(enabled: boolean): void {
  const win = getWin();
  if (!win) return;
  const settings = getLensSettings();
  overlayStyleApplied = enabled;
  if (enabled) {
    normalBounds = win.getBounds();
    overlayLockedSize = overlayBounds
      ? { width: overlayBounds.width, height: overlayBounds.height }
      : { width: normalBounds.width, height: normalBounds.height };
    win.setOpacity(settings.opacity);
    // macOS: follow the user to whatever Space/full-screen app they're on, so
    // showing the overlay never switches Spaces. Joining a full-screen Space as
    // an auxiliary window only works while the window itself is not
    // fullscreenable, and the window level must be raised after the collection
    // behavior is set. skipTransformProcessType keeps the Dock icon stable.
    if (process.platform === "darwin") {
      win.setFullScreenable(false);
      win.setVisibleOnAllWorkspaces(true, { visibleOnFullScreen: true, skipTransformProcessType: true });
    }
    win.setAlwaysOnTop(true, "screen-saver");
    win.setIgnoreMouseEvents(!settings.hoverMode, { forward: true });
    win.setResizable(false);
    win.removeListener("will-resize", preventOverlayResize);
    win.removeListener("resize", guardOverlayResize);
    win.on("will-resize", preventOverlayResize);
    win.on("resize", guardOverlayResize);
    win.webContents
      .executeJavaScript(
        `document.body.classList.add('overlay');${
          settings.hoverMode ? `document.body.classList.add('hover-mode');` : `document.body.classList.remove('hover-mode');`
        }`,
      )
      .catch(() => {});
    if (overlayBounds) win.setBounds(overlayBounds);
  } else {
    overlayLockedSize = null;
    win.removeListener("will-resize", preventOverlayResize);
    win.removeListener("resize", guardOverlayResize);
    overlayBounds = win.getBounds();
    win.setOpacity(1.0);
    win.setAlwaysOnTop(false);
    if (process.platform === "darwin") {
      win.setVisibleOnAllWorkspaces(false, { skipTransformProcessType: true });
    }
    win.setIgnoreMouseEvents(false);
    win.setResizable(true);
    win.webContents.executeJavaScript(`document.body.classList.remove('overlay','hover-mode');`).catch(() => {});
    if (normalBounds) win.setBounds(normalBounds);
  }
}

const FADE_IN_DURATION_MS = 160;
const FADE_OUT_DURATION_MS = 320;
const FADE_INTERVAL_MS = 16;
let fadeTimer: ReturnType<typeof setInterval> | null = null;

export function stopFade(): void {
  if (fadeTimer) {
    clearInterval(fadeTimer);
    fadeTimer = null;
  }
}

// The window is never destroyed while hidden — its content stays fully rendered — so a
// plain win.show()/hide() reveals the finished layout instantly and only then plays
// Windows' own native reveal animation, producing a flash-then-animate glitch. Driving
// opacity ourselves in small steps gives one smooth, consistent transition instead.
function fadeWindowOpacity(target: number, duration: number, onComplete?: () => void): void {
  const win = getWin();
  if (!win) return;
  stopFade();
  const start = win.getOpacity();
  const startTime = Date.now();
  fadeTimer = setInterval(() => {
    const w = getWin();
    if (!w) {
      stopFade();
      return;
    }
    const t = Math.min(1, (Date.now() - startTime) / duration);
    w.setOpacity(start + (target - start) * t);
    if (t >= 1) {
      stopFade();
      onComplete?.();
    }
  }, FADE_INTERVAL_MS);
}

export function createOverlayWindow(onReady: () => void): BrowserWindow {
  const { width, height } = screen.getPrimaryDisplay().workAreaSize;

  const w = new BrowserWindow({
    width: Math.min(1270, width),
    height: Math.min(560, height),
    show: false,
    frame: false,
    transparent: true,
    backgroundColor: "#00000000",
    alwaysOnTop: false,
    skipTaskbar: true,
    // Required on macOS for visibleOnFullScreen (fullScreenAuxiliary) to stick.
    fullscreenable: false,
    // macOS: a non-activating NSPanel is the only window kind that can float
    // over other apps' full-screen Spaces without transforming the process to
    // UIElement (which would hide Bazecor's Dock icon).
    ...(process.platform === "darwin" ? { type: "panel" as const } : {}),
    webPreferences: {
      preload: LENS_WINDOW_PRELOAD_WEBPACK_ENTRY,
      contextIsolation: true,
      nodeIntegration: false,
      backgroundThrottling: false,
    },
  });

  LensOverlay.setWindow(w);
  w.loadURL(LENS_WINDOW_WEBPACK_ENTRY);

  w.once("ready-to-show", () => {
    log.info("[Lens] Overlay window ready-to-show");
    overlayVisible = true;
    applyOverlayMode(true);
    // showInactive: an overlay must never activate Bazecor — on macOS a plain
    // show() focuses the app, yanking the user out of whatever they're doing.
    w.showInactive();
    onReady();
  });

  w.webContents.setVisualZoomLevelLimits(1, 1);

  w.on("closed", () => {
    LensOverlay.setWindow(null);
    overlayVisible = false;
    overlayStyleApplied = false;
  });

  return w;
}

export function destroyOverlayWindow(): void {
  stopFade();
  const win = getWin();
  if (win && !win.isDestroyed()) {
    // Remember position/size for the next enable.
    if (overlayStyleApplied) overlayBounds = win.getBounds();
    win.destroy();
  }
  LensOverlay.setWindow(null);
  overlayVisible = false;
  overlayStyleApplied = false;
  overlayLockedSize = null;
}

export function showOverlay(): void {
  const win = getWin();
  if (!win) return;
  overlayVisible = true;
  const settings = getLensSettings();
  // Only (re)apply overlay styling (bounds/opacity/always-on-top/CSS) once; hideOverlay()
  // never tears it down, so reapplying it on every show causes a visible flash.
  if (settings.overlayMode && !overlayStyleApplied) applyOverlayMode(true);
  const target = overlayStyleApplied ? settings.opacity : 1.0;
  win.setOpacity(0);
  if (overlayStyleApplied) win.showInactive();
  else win.show();
  fadeWindowOpacity(target, FADE_IN_DURATION_MS);
}

export function hideOverlay(): void {
  const win = getWin();
  if (!win) return;
  overlayVisible = false;
  fadeWindowOpacity(0, FADE_OUT_DURATION_MS, () => {
    getWin()?.hide();
  });
}

export function setOverlayShown(shown: boolean): void {
  const win = getWin();
  if (!win) return;
  overlayVisible = shown;
  if (shown) {
    applyOverlayMode(true);
    win.showInactive();
  } else {
    applyOverlayMode(false);
    win.hide();
  }
}

export function applyOpacityLive(v: number): void {
  if (overlayStyleApplied) getWin()?.setOpacity(v);
}

export function applyHoverModeLive(v: boolean): void {
  const win = getWin();
  if (!win || !overlayStyleApplied) return;
  win.setIgnoreMouseEvents(!v, { forward: true });
  win.webContents
    .executeJavaScript(v ? `document.body.classList.add('hover-mode');` : `document.body.classList.remove('hover-mode');`)
    .catch(() => {});
}

// ── Overlay drag / resize (driven by the overlay renderer in hover mode) ──────

export function overlayMove(x: number, y: number): void {
  const win = getWin();
  if (!win) return;
  // Absolute positioning: the renderer computes the target top-left from the
  // cursor's screen position minus the grab offset, so it self-corrects every
  // frame and never accumulates. We must NOT read position back from
  // getBounds() (DWM rounding on transparent/frameless Windows drifts it).
  // Pin the size to the intended overlay size so a move can never resize.
  const { width, height } = win.getBounds();
  const w = overlayLockedSize?.width ?? width;
  const h = overlayLockedSize?.height ?? height;
  win.setBounds({ x: Math.round(x), y: Math.round(y), width: w, height: h });
}

export function overlayMoveBy(dx: number, dy: number): void {
  const win = getWin();
  if (!win) return;
  const { x, y, width, height } = win.getBounds();
  const w = overlayLockedSize?.width ?? width;
  const h = overlayLockedSize?.height ?? height;
  win.setBounds({ x: x + Math.round(dx), y: y + Math.round(dy), width: w, height: h });
}

export function overlayResize(dir: string, dx: number, dy: number): void {
  const win = getWin();
  if (!win) return;
  const [wx, wy] = win.getPosition();
  const [ww, wh] = win.getSize();
  let nx = wx;
  let ny = wy;
  let nw = ww;
  let nh = wh;
  if (dir.includes("e")) nw = Math.max(400, ww + dx);
  if (dir.includes("s")) nh = Math.max(200, wh + dy);
  if (dir.includes("w")) {
    nx = wx + dx;
    nw = Math.max(400, ww - dx);
  }
  if (dir.includes("n")) {
    ny = wy + dy;
    nh = Math.max(200, wh - dy);
  }
  if (overlayLockedSize) overlayLockedSize = { width: nw, height: nh };
  win.setBounds({ x: nx, y: ny, width: nw, height: nh });
}

// ── Push helpers (main → overlay renderer) ────────────────────────────────────

export function pushModel(model: KeyboardModel): void {
  if (overlayAlive()) getWin()!.webContents.send("lens:model", model);
}

export function pushActiveLayer(layer: number): void {
  if (overlayAlive()) getWin()!.webContents.send("lens:active-layer", layer);
}

export function pushState(state: LensState): void {
  if (overlayAlive()) getWin()!.webContents.send("lens:state", state);
}

/** Sends state to the overlay AND the main Bazecor window (used for changes the
 * settings UI must react to, e.g. the macOS Input Monitoring permission banner). */
export function broadcastState(state: LensState): void {
  pushState(state);
  const main = Window.getWindow();
  if (main && !main.isDestroyed()) main.webContents.send("lens:state", state);
}

/** Sends settings to the overlay AND the main Bazecor window so both UIs stay in sync. */
export function broadcastSettings(settings: LensSettings): void {
  if (overlayAlive()) getWin()!.webContents.send("lens:settings", settings);
  const main = Window.getWindow();
  if (main && !main.isDestroyed()) main.webContents.send("lens:settings", settings);
}
