import { BrowserWindow, app } from "electron";
import windowStateKeeper from "electron-window-state";
import path from "path";
import log from "electron-log/main";
import { configureNativeTheme } from "./setup/theme";
import { configureIPCs } from "./setup/configureIPCs";
import configureRedirect from "./setup/configureRedirect";
import onDevTools from "./setup/onDevTools";
import onReadyToShow from "./setup/onReadyToShow";
import onClose from "./setup/onClose";
import Window from "./managers/Window";
import { configureUSB } from "./setup/configureUSB";
import { configureHID, removeHIDListeners } from "./setup/configureHID";

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;

const createWindow = () => {
  // Create the browser window.
  const mainWindowState = windowStateKeeper({
    defaultWidth: 1200,
    defaultHeight: 900,
  });

  const mainWindow = new BrowserWindow({
    x: mainWindowState.x,
    y: mainWindowState.y,
    width: mainWindowState.width,
    height: mainWindowState.height,
    minWidth: 650,
    minHeight: 570,
    resizable: true,
    icon: path.join("../renderer/static", "/logo.png"),
    show: false,
    backgroundColor: "#2e2c29",
    webPreferences: {
      sandbox: false,
      nodeIntegration: true,
      contextIsolation: false,
      webSecurity: false,
      backgroundThrottling: false,
    },
  });

  mainWindow.on("close", () => {
    removeHIDListeners();
  });

  configureIPCs();
  mainWindowState.manage(mainWindow);

  // and load the index.html of the app.
  if (MAIN_WINDOW_VITE_DEV_SERVER_URL) {
    mainWindow.loadURL(MAIN_WINDOW_VITE_DEV_SERVER_URL);
    log.info(`Loading Vite dev server URL: ${MAIN_WINDOW_VITE_DEV_SERVER_URL}`);
  } else {
    mainWindow.loadFile(path.join(__dirname, `../renderer/${MAIN_WINDOW_VITE_NAME}/index.html`));
  }

  Window.getInstance(); // init Windows manager
  Window.setWindow(mainWindow);
  if (!app.isPackaged) {
    // Open the DevTools if we are in development mode
    mainWindow.webContents.openDevTools();
  }

  configureNativeTheme();
  configureRedirect();
  onReadyToShow();
  onDevTools();
  onClose();
  configureHID();
  configureUSB();
};

export default createWindow;
